using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using System.Windows.Data;

namespace Automation.Shared.ViewModels
{
    [Flags]
    public enum EnumScopedType
    {
        Scope,
        Workflow,
        Task
    }

    [JsonDerivedType(typeof(ScopedTask), typeDiscriminator: "node")]
    [JsonDerivedType(typeof(Scope), typeDiscriminator: "scope")]
    public class ScopedElement : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        { PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName)); }

        // XXX : Guid.NewGuid() not good, should be generated by the database
        public Guid Id { get; set; } = Guid.NewGuid();

        public Guid? ParentId { get; set; }

        [JsonIgnore]
        public Scope? Parent { get; set; }

        public string Name { get; set; }

        public EnumScopedType Type { get; set; }

        // TODO : Handle different type of objects
        public Dictionary<string, string> Context { get; set; } = new Dictionary<string, string>();

        [JsonIgnore]
        public bool IsExpanded { get; set; }

        private bool _isSelected;
        [JsonIgnore]
        public bool IsSelected
        {
            get { return _isSelected; }
            set
            {
                _isSelected = value;

                // Since we are using a treeview, we need to expand the parent when
                // a child is selected (otherwise the selection will not go through)
                if (value)
                {
                    ExpandParent();
                    IsExpanded = true;
                }

                OnPropertyChanged();
            }
        }

        public void ExpandParent()
        {
            if (Parent == null)
                return;

            Parent.ExpandParent();
            Parent.IsExpanded = true;
        }
    }

    // XXX : Not to sure if ScopedTask should exist, could use only the relationship from TaskNode.ParentScopeId
    // XXX : Question are : Does a task need a specific context ? Get all the tasks from a scope and display them in a tree ?
    public class ScopedTask : ScopedElement
    {
        public Guid TaskId { get; set; }

        public ScopedTask()
        {}

        public ScopedTask(TaskNode node)
        {
            TaskId = node.Id;
            Name = node.Name;
            if (node is WorkflowNode)
                Type = EnumScopedType.Workflow;
            else if (node is TaskNode)
                Type = EnumScopedType.Task;
        }
    }

    public class Scope : ScopedElement
    {
        [JsonIgnore]
        public ObservableCollection<ScopedElement> Childrens { get; set; } = [];
        [JsonIgnore]
        public ListCollectionView SortedChildrens { get; set; }

        public Scope()
        {
            Type = EnumScopedType.Scope;
            SortedChildrens = (ListCollectionView)CollectionViewSource.GetDefaultView(Childrens);
            SortedChildrens.SortDescriptions.Add(new SortDescription(nameof(Type), ListSortDirection.Ascending));
            SortedChildrens.SortDescriptions.Add(new SortDescription(nameof(Name), ListSortDirection.Ascending));
        }

        public void AddChild(ScopedElement element)
        {
            element.Parent = this;
            Childrens.Add(element);
        }
    }
}
