<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Joufflu" Version="0.5.1" />
    <PackageReference Include="Joufflu.Feedback" Version="0.5.0" />
    <PackageReference Include="Joufflu.Inputs" Version="0.5.2" />
    <PackageReference Include="Joufflu.Navigation" Version="0.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation.Services.Local\Automation.Services.Local.csproj" />
    <ProjectReference Include="..\Automation.Shared\Automation.Shared.csproj" />
  </ItemGroup>

</Project>
