version: '3.4'
services:
  automation.api.supervisor:
    image: ${DOCKER_REGISTRY-}automationapisupervisor
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Automation.Api.Supervisor/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nugetlocal:/app/data/nuget

  automation.api.worker:
    image: ${DOCKER_REGISTRY-}automationapiworker
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Automation.Api.Worker/Dockerfile
    env_file:
      - .env

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --auth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongodb-data:
    driver: local