version: '3.4'
services:
  automation.supervisor.api:
    image: ${DOCKER_REGISTRY-}automationapisupervisor
    depends_on:
      - mongo
      - redis
    build:
      context: .
      dockerfile: Automation.Supervisor.Api/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./volumes/nugetlocal:/app/data/nuget

  automation.worker.service:
    image: ${DOCKER_REGISTRY-}automationworkerservice
    depends_on:
      - mongo
      - redis
    build:
      context: .
      dockerfile: Automation.Worker.Service/Dockerfile
    env_file:
      - .env
    environment:
      - WORKER_ID=DEFAULT_WORKER
    volumes:
      - ./volumes/nugetlocal:/app/data/nuget

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --auth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

# For worker communication with clients and supervisor
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]

volumes:
  mongodb-data:
    driver: local